org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=sihriya
mod_name=Sihriya
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=tong.sihriya
mod_authors=ela_juff
mod_description=Un syst\u00E8me de magie \u00E9l\u00E9mentaire avec mana, \u00E9coles et progression.
