@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tong.sihriya.animation;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
