@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tong.sihriya.projectile;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
